### ISSUE TITLE
Not published on bower 

### ISSUE THREAD

**Issue by bmherold** [epoberezkin/ajv-i18n#28]
Not published on bower - could ya publish this? Thanks!

**Comment by epoberezkin** [comment]
I have published, I thought it is...
Please see https://github.com/epoberezkin/ajv-i18n#install

It could be easier to use with npm, if the bundle were published there (it's not at the moment). Using with browserify/webpack seems better though, as you can inlude only the languages you need, rather than loading all of them in a separate bundle.

**Comment by bmherold** [comment]
Whats the expected way to use this? 

If I pull it in with npm or bower ("ajv-i18n": "epoberezkin/ajv-i18n#^1.3.0") it still needs to be built with 'npm install && npm run bundle-all'. 

At that point, it's been browserified, and I can use it in my project by doing a `require('/localize/index')`. Can you explain why the require doesnt follow the example `require('ajv-i18n')`?
